version: 2.1

executors:
  terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
  tfsec:
    docker:
      - image: aquasec/tfsec-ci:latest

environment:
  variables:
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

jobs:

  tfsec:
    executor: tfsec
    steps:
      - checkout
      - run: 
          name: tfsec
          command: |
            tfsec . -s

  terraform-plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Init and validate
          command: |
            terraform init -backend-config=dev_backend.hcl
            echo "Terrafom Validation"
            terraform validate
            terraform plan -var-file=dev.tfvars


  terraform-apply:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Apply 
          command: |
            terraform init -backend-config=dev_backend.hcl
            terraform apply -var-file=dev.tfvars

workflows:
  build_approve_deploy:
    jobs:
      - tfsec
      - terraform-plan:
          requires:
            - tfsec
      - hold:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - hold

