version: 2.1

executors:
  terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
  tfsec:
    docker:
      - image: aquasec/tfsec-ci:latest

environment:
  variables:
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

jobs:

  tfsec:
    executor: tfsec
    steps:
      - checkout
      - run: 
          name: tfsec
          command: |
            tfsec . -s

  terraform-plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Init, validate and Plan
          command: |
            terraform init -backend-config=${BACKEND_CONFIG}
            echo "*** Terraform Validation ***"
            terraform validate
            terraform plan -var-file=${VAR_FILE}

  terraform-apply:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Apply 
          command: |
            terraform init -backend-config=${BACKEND_CONFIG}
            terraform apply -var-file=${VAR_FILE}

workflows:
  build_approve_deploy:
    jobs:
      - tfsec
      - terraform-plan:
          requires:
            - tfsec
          environment:
            BACKEND_CONFIG: dev_backend.hcl
            VAR_FILE: dev.tfvars
          filters:
            branches:
              only:
                - main
      - terraform-apply:
          requires:
            - terraform-plan
          environment:
            BACKEND_CONFIG: dev_backend.hcl
            VAR_FILE: dev.tfvars
          filters:
            branches:
              only:
                - dev
      - terraform-plan:
          requires:
            - tfsec
          environment:
            BACKEND_CONFIG: test_backend.hcl
            VAR_FILE: test.tfvars
          filters:
            branches:
              only:
                - test
      - terraform-apply:
          requires:
            - terraform-plan
          environment:
            BACKEND_CONFIG: test_backend.hcl
            VAR_FILE: test.tfvars
          filters:
            branches:
              only:
                - test
      - terraform-plan:
          requires:
            - tfsec
          environment:
            BACKEND_CONFIG: prod_backend.hcl
            VAR_FILE: prod.tfvars
          filters:
            branches:
              only:
                - master
      - terraform-apply:
          requires:
            - terraform-plan
          environment:
            BACKEND_CONFIG: prod_backend.hcl
            VAR_FILE: prod.tfvars
          filters:
            branches:
              only:
                - master
